### ISSUE TITLE
navigator is not defined

### ISSUE THREAD

**Issue by catfishlty** [LarchLiu/vue3-video-player#35]
使用Nuxt3 `3.0.0-rc.11`后报错

```
[nuxt] [request error] [unhandled] [500] navigator is not defined
  at Module.fb15 (E:\WebstormProjects\test-web\node_modules\@cloudgeek\vue3-video-player\dist\vue3-video-player.common.js:22733:10)
  at __webpack_require__ (E:\WebstormProjects\test-web\node_modules\@cloudgeek\vue3-video-player\dist\vue3-video-player.common.js:21:30)
  at E:\WebstormProjects\test-web\node_modules\@cloudgeek\vue3-video-player\dist\vue3-video-player.common.js:85:18
  at Object.<anonymous> (E:\WebstormProjects\test-web\node_modules\@cloudgeek\vue3-video-player\dist\vue3-video-player.common.js:88:10)
  at Module._compile (internal/modules/cjs/loader.js:1063:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
  at Module.load (internal/modules/cjs/loader.js:928:32)
  at Function.Module._load (internal/modules/cjs/loader.js:769:14)
  at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
  at ModuleJob.run (internal/modules/esm/module_job.js:152:23)

```

**Comment by LarchLiu** [comment]
Sorry, It's not support ssr now. #29
