### ISSUE TITLE
downgradeCore is not a function after change hls video resolution

### ISSUE THREAD

**Issue by kotovi** [LarchLiu/vue3-video-player#38]
Hello!
Randomly get error when change video resolution (
the error also occurs in your demo https://stackblitz.com/edit/vitejs-vite-rf6dum?file=src%2FApp.vue)
{type: 'otherError', details: 'internalException', fatal: false, event: 'hlsError', error: TypeError: _this6.downgradeCore is not a function
    at Object.<anonymous> (https://vitejsviterf6d…, …}
index.js:121 {type: 'otherError', details: 'internalException', fatal: false, event: 'hlsError', error: TypeError: _this6.downgradeCore is not a function
    at Object.<anonymous> (https://vitejsviterf6d…, …}
index.js:121 {type: 'otherError', details: 'internalException', fatal: false, event: 'hlsError', error: TypeError: _this6.downgradeCore is not a function
    at Object.<anonymous> (https://vitejsviterf6d…, …}
index.js:121 {type: 'otherError', details: 'internalException', fatal: false, event: 'hlsError', error: TypeError: _this6.downgradeCore is not a function
    at Object.<anonymous> (https://vitejsviterf6d…, …}

With what it can be ?
With best regards

**Comment by kotovi** [comment]
Object
details
: 
"internalException"
error
: 
TypeError: e.downgradeCore is not a function at Object.<anonymous> (https://../js/chunk-vendors.b6737eeb.js:10:192097) at Object.o (https://../js/chunk-vendors.b6737eeb.js:18:170746) at Proxy.emit (https://school.eurekacenter.ru/js/chunk-vendors.b6737eeb.js:18:198915) at Y.value (https://school.eurekacenter.ru/js/chunk-vendors.b6737eeb.js:10:194842) at Proxy.<anonymous> (https://school.eurekacenter.ru/js/chunk-vendors.b6737eeb.js:10:254432) at o.emit (https://cdn.jsdelivr.net/npm/hls.js@latest:1:188403) at e.emit (https://cdn.jsdelivr.net/npm/hls.js@latest:1:365691) at e.trigger (https://cdn.jsdelivr.net/npm/hls.js@latest:1:365789) at e.trigger (https://cdn.jsdelivr.net/npm/hls.js@latest:1:365937) at e.trigger (https://cdn.jsdelivr.net/npm/hls.js@latest:1:365937)
message
: 
"e.downgradeCore is not a function"
stack
: 
"TypeError: e.downgradeCore is not a function\n    at Object.<anonymous> (../js/chunk-vendors.b6737eeb.js:10:192097)\n    at Object.o (../js/chunk-vendors.b6737eeb.js:18:170746)\n    at Proxy.emit (../js/chunk-vendors.b6737eeb.js:18:198915)\n    at Y.value (.../js/chunk-vendors.b6737eeb.js:10:194842)\n    at Proxy.<anonymous> (.../js/chunk-vendors.b6737eeb.js:10:254432)\n    at o.emit (https://cdn.jsdelivr.net/npm/hls.js@latest:1:188403)\n    at e.emit (https://cdn.jsdelivr.net/npm/hls.js@latest:1:365691)\n    at e.trigger (https://cdn.jsdelivr.net/npm/hls.js@latest:1:365789)\n    at e.trigger (https://cdn.jsdelivr.net/npm/hls.js@latest:1:365937)\n    at e.trigger (https://cdn.jsdelivr.net/npm/hls.js@latest:1:365937)"
[[Proto
